name: Build and deploy Node.js app to Azure Web App - ChuckBot

on:
  push:
    branches:
      - with-fixes
  workflow_dispatch:

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: "18.x"

      - name: Login to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: npm install and build
        run: |
          npm install
          npm run build --if-present

      - name: Zip artifact for deployment
        run: zip -r release.zip .

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: "ChuckBot"
          slot-name: "Production"
          package: release.zip

      - name: Set Environment Variables in Azure Web App
        run: |
          az webapp config appsettings set --name "ChuckBot" --resource-group "ChuckBot_group-b318" --settings TELEGRAM_TOKEN=${{ secrets.TELEGRAM_TOKEN }} TRANSLATOR_TEXT_SUBSCRIPTION_KEY=${{ secrets.TRANSLATOR_TEXT_SUBSCRIPTION_KEY }} LOCATION=${{ secrets.LOCATION }}

